services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ex1-12
    ports:
      - 5000:5000
    depends_on:
      - redis
      - postgres
    container_name: web-frontend 

  backend:
    build:
      context: .
      dockerfile: Dockerfile.ex1-13
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=test
    depends_on:
      - redis
      - postgres
    container_name: web-backend

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis-db

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    container_name: postgres-db
