FROM node:16-alpine AS build-stage
ENV REACT_APP_BACKEND_URL=http://localhost:8080
WORKDIR /usr/home

COPY material-applications/example-frontend .

RUN npm install && npm run build


FROM node:16-alpine
EXPOSE 5000
WORKDIR /usr/home
COPY --from=build-stage /usr/home/build /usr/home/build
RUN npm install -g serve && \
    adduser -D appuser && chown appuser .

CMD ["serve", "-s", "-l", "5000", "build"]

