FROM ubuntu:latest
EXPOSE 5000
ENV REACT_APP_BACKEND_URL=http://localhost:80
WORKDIR /usr/src

COPY material-applications/example-frontend .

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash && apt install -y nodejs && npm install && npm run build && \
    npm install -g serve && useradd -m appuser && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
